import Navbar from "@/components/navbar"

export const metadata = {
    title: 'Auth',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
    <main>
        <Navbar/>
        <>{children}</>
    </main>
    )
  }
  