export const products = [
    {
        "id": 1,
        "shop_id": 1,
        "name": "product 1 shop 1",
        "image": "https://images.tokopedia.net/img/cache/700/VqbcmM/2023/10/17/cdf14460-ce09-47e6-8913-fdf63b4350b1.jpg.webp?ect=4g",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "stock": 3,
        "price": 120000,
    },
    {
        "id": 2,
        "shop_id": 1,
        "name": "product 2 shop 1 Test Long Test Awikwok Awikadaw Blok",
        "image": "https://images.tokopedia.net/img/cache/900/VqbcmM/2023/10/18/ab4dbbcd-c012-4b79-84da-fc1368a882f7.jpg",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "stock": 10,
        "price": 2000000,
    },
    {
        "id": 3,
        "shop_id": 1,
        "name": "product 3 shop 1",
        "image": "https://images.tokopedia.net/img/cache/700/VqbcmM/2022/9/16/c8a42850-61f8-4dda-946b-5f2b3b3018d2.jpg.webp?ect=4g",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "stock": 2,
        "price": 12000000,
    },
    {
        "id": 4,
        "shop_id": 2,
        "name": "product 1 shop 2 Macbook",
        "image": "https://images.tokopedia.net/img/cache/900/hDjmkQ/2024/11/6/9c5fbf66-f285-48ba-a930-1ef9a3e1a70b.jpg",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "stock": 1,
        "price": 16700000,
    },
    {
        "id": 5,
        "shop_id": 2,
        "name": "product 2 shop 2 Harga Ratusan Juta",
        "image": "https://images.tokopedia.net/img/cache/900/hDjmkQ/2024/12/6/b5814925-f068-4919-9a77-0e39594406a4.jpg",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "stock": 1,
        "price": 200000000,
    },
    {
        "id": 6,
        "shop_id": 2,
        "name": "product 3 shop 1 Mainan Anak Anak",
        "image": "https://images.tokopedia.net/img/cache/700/VqbcmM/2022/9/16/c8a42850-61f8-4dda-946b-5f2b3b3018d2.jpg.webp?ect=4g",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "stock": 1,
        "price": 200000,
    },
    {
        "id": 7,
        "shop_id": 3,
        "name": "product 1 shop 3 Ipad 10",
        "image": "https://images.tokopedia.net/img/cache/900/hDjmkQ/2024/12/6/b5814925-f068-4919-9a77-0e39594406a4.jpg",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "stock": 1,
        "price": 5160000,
    },
]
